apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - image: docker.io/palsha/golshi:latest
        name: go-deploy
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_DSN
          valueFrom:
            secretKeyRef:
              name: go-sec
              key: rickey
        command: ['/golshi/main']
      
